### PR TITLE
feat: add cv.magnitude

### PR DESCRIPTION
**Pull request by s-g-1**
Have picked up #50  as a `first good issue`.
Any feedback gratefully received.
Thx.

### CODE REVIEW

**Comment by piercus** [comment]
@s-g-1 thanks for your work

**Comment by UrielCh** [comment]
Is the unit test error message clear enough?

I still have some cleaning up to do in the testing portion of the project.

**Comment by s-g-1** [comment]
Not really tbh, it looks like a build failure rather than any thing to do with the added code? I'm not familiar with appveyor or what it needs to get running correctly?

**Comment by UrielCh** [comment]
Please disregard the AppVeyor error for the moment.

I resolved this issue in another branch, but it appears I forgot to merge it. My apologies for any oversight.

On a personal note, I'm currently going through a challenging period as I am without a home or job, and my belongings are trapped in a war zone.

Your understanding and patience during this difficult time are greatly appreciated.

**Comment by UrielCh** [comment]
it's looks like the patch for appveyor is merged on master: https://github.com/UrielCh/opencv4nodejs/commit/55fcd8a3d2b51aa00dc498d07053c86b020cac91

**Comment by s-g-1** [comment]
Hey, really sorry to hear about your situation.
No pressure from my side, I'm just keen to help out. Hopefully this latest update will fix my mistake in the test.

**Comment by s-g-1** [comment]
Going to try commenting out my changes to see if the build will run.

**Comment by s-g-1** [comment]
@piercus or @UrielCh sorry for the delay. I've commented out my changes and pushed again to force a rebuild using appveyor. It still fails when node_gpy attempts to load a deprecated python library DISTUTILS (or similar) which was removed in Python3.12 and not updated by the node-gyp team until v10. My thinking is that the appveyor build would have worked until it started using Py3.12.

I have bumped node-gyp to 10.0.1 [& pnpm to 8.6.2] in package.json but can't build on my local to rebuild pnpm-lock.yaml. I think this is all that's needed to get the build working again. Once this is in place, I'll reintroduce my changes.

Thx.

**Comment by UrielCh** [comment]
I'm responsible for addressing all issues related to GitHub Actions. :)

let me check.

**Comment by UrielCh** [comment]
Please can you improve your test code
```
    const expectOutput = (res: Mat) => {
      expect(res).to.be.instanceOf(cv.Mat);
    };
```

your are only testing the return type, can you enforce the check of the content of the res Matrix ?

**Comment by UrielCh** [comment]
`All checks have passed`
then this PR will be merge.

**Pull request merged**
